In [1]:
import numpy as np

In [2]:
x = np.array([np.random.randn(2), np.random.randn(2)]) 

In [3]:
print(x)

[[-0.55180042 -0.28045323]
 [ 0.05897622 -0.31134741]]


In [4]:
x.size

4

In [5]:
x.dtype

dtype('float64')

In [6]:
x = np.array([np.random.randn(2), np.random.randn(2)], dtype=np.float) 

In [7]:
print(x)

[[ 1.08783474 -1.05192939]
 [ 1.05843612  0.20689489]]


In [8]:
x.size

4

In [9]:
x.dtype

dtype('float64')

In [10]:
y=np.transpose(x)

In [11]:
a=np.add(x,y)

In [12]:
print(a)

[[ 2.17566947  0.00650673]
 [ 0.00650673  0.41378979]]


In [13]:
b=np.multiply(x,y)

In [14]:
print(b)

[[ 1.18338441 -1.11340006]
 [-1.11340006  0.0428055 ]]
